{
  "formatVersion": "1.1",
  "component": {
    "group": "avail",
    "module": "avail-plugin",
    "version": "1.6.1.rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "avail-plugin-1.6.1.rc1.jar",
          "url": "avail-plugin-1.6.1.rc1.jar",
          "size": 66929,
          "sha512": "af37dc9fc50af020d2e94893ec2146ac7469409c577be6573c70aeec654619e39e494d1f963176d8587a8c681a12abde79c61bc94eb5bdef3cb8ae79a996b5ef",
          "sha256": "f0d73d189e754d9239653cfe162b6c346fba977e632af304940879367e4abaa3",
          "sha1": "0d2bc6df2cee9a42ebbe3577d69865335396b418",
          "md5": "8c4f434fd254fad12879cfa9b92ae91b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "avail-plugin-1.6.1.rc1.jar",
          "url": "avail-plugin-1.6.1.rc1.jar",
          "size": 66929,
          "sha512": "af37dc9fc50af020d2e94893ec2146ac7469409c577be6573c70aeec654619e39e494d1f963176d8587a8c681a12abde79c61bc94eb5bdef3cb8ae79a996b5ef",
          "sha256": "f0d73d189e754d9239653cfe162b6c346fba977e632af304940879367e4abaa3",
          "sha1": "0d2bc6df2cee9a42ebbe3577d69865335396b418",
          "md5": "8c4f434fd254fad12879cfa9b92ae91b"
        }
      ]
    }
  ]
}
