org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx6g -XX:+UseCompressedOops

kotlin.stdlib.default.dependency=true
org.gradle.warning.mode=all
kotlin.incremental=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.daemon.max.heap.size=8g
org.gradle.configuration-cache=true
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true
