/*
 * A_RegisterDump.kt
 * Copyright © 1993-2022, The Avail Foundation, LLC.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of the copyright holder nor the names of the contributors
 *   may be used to endorse or promote products derived from this software
 *   without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package avail.descriptor.functions

import avail.descriptor.functions.A_RegisterDump.Companion.decodeBoxedValueFromDump
import avail.descriptor.functions.A_RegisterDump.Companion.encodeLocalValue
import avail.descriptor.functions.A_RegisterDump.Companion.encodedElidedLocals
import avail.descriptor.functions.RegisterDumpDescriptor.ObjectSlots.ENCODED_ELIDED_LOCALS
import avail.descriptor.numbers.DoubleDescriptor.Companion.fromDouble
import avail.descriptor.numbers.IntegerDescriptor.Companion.fromInt
import avail.descriptor.representation.A_BasicObject
import avail.descriptor.representation.A_BasicObject.Companion.dispatch
import avail.descriptor.representation.AvailObject
import avail.descriptor.tuples.A_Tuple
import avail.exceptions.unsupported
import avail.interpreter.levelTwo.L2Chunk
import avail.interpreter.levelTwo.register.BOXED_KIND
import avail.interpreter.levelTwo.register.FLOAT_KIND
import avail.interpreter.levelTwo.register.INTEGER_KIND
import avail.interpreter.levelTwo.register.RegisterKind
import avail.optimizer.DefaultL1ExecutableChunk.DefaultEntryPoint
import avail.optimizer.DefaultL1ExecutableChunk.DefaultL1Chunk
import avail.optimizer.L2Generator
import avail.optimizer.jvm.CheckedMethod
import avail.optimizer.jvm.CheckedMethod.Companion.instanceMethod
import avail.optimizer.jvm.ReferencedInGeneratedCode
import avail.utility.cast
import java.lang.Double.longBitsToDouble

/**
 * [A_RegisterDump] is an interface for
 * [register&#32;dumps][RegisterDumpDescriptor] created for reification within
 * an [L2Chunk], generated by the [L2Generator].
 *
 * @author Mark van Gulik &lt;mark@availlang.org&gt;
 */
interface A_RegisterDump : A_BasicObject
{
	/**
	 * Given a continuation register dump, extract the object at the given
	 * slot index.
	 *
	 * @param index
	 *   The index at which to extract an [AvailObject].
	 * @return
	 *   The extracted [AvailObject].
	 */
	@ReferencedInGeneratedCode
	fun extractDumpedObjectAt(index: Int): AvailObject

	/**
	 * Given a continuation register dump, extract the [Long] at the given
	 * slot index.
	 *
	 * @param index
	 *   The index at which to extract a [Long].
	 * @return
	 *   The extracted [Long].
	 */
	@ReferencedInGeneratedCode
	fun extractDumpedLongAt(index: Int): Long

	/**
	 * Given a continuation register dump, extract the [DefaultEntryPoint] that
	 * indicates where it will continue within the [DefaultL1Chunk] if the
	 * containing continuation becomes immutable or shared.
	 *
	 * @return
	 *   The [DefaultEntryPoint] for continuing in the [DefaultL1Chunk].
	 */
	val fallbackEntryPoint: Int

	companion object {
		/**
		 * Encode a reference to a register that has been saved in a register
		 * dump, in such a way that it can be decoded later if the continuation
		 * using the dump is made immutable or shared.
		 *
		 * See [decodeBoxedValueFromDump] for the corresponding decoding logic.
		 *
		 * Boxed values are written as a one-based index into the dumped object
		 * array.
		 *
		 * Int values are written as the zero-based index × -2 into the dumped
		 * long array, where a [Long] slot holds the [Int].
		 *
		 * Double values are written as the zero-based index × -2 + 1 into the
		 * dumped long array, where the [Long] slot holds the raw bit pattern
		 * for reconstructing a [Double].
		 *
		 * @param kind
		 *   The [RegisterKind] of the register that held the local variable
		 *   value.
		 * @param liveIndexInKind
		 *   A zero-based index into the boxed, integer, or float register list
		 *   saved in some dump.
		 * @return
		 *   An encoded [Int] to save in the dump's [encodedElidedLocals], to
		 *   allow a specified elided local variable to be initialized on
		 *   creation, if the continuation using the dump is made immutable or
		 *   shared.
		 */
		fun encodeLocalValue(
			kind: RegisterKind<*>,
			liveIndexInKind: Int
		): Int
		{
			assert(liveIndexInKind >= 0)
			return when (kind)
			{
				BOXED_KIND -> liveIndexInKind + 1
				INTEGER_KIND -> liveIndexInKind * -2 - 2
				FLOAT_KIND -> liveIndexInKind * -2 + 1
			}
		}

		/**
		 * Decode a reference to a register that has been saved in a dump for
		 * the purpose of initializing an elided variable during creation and
		 * initialization when the [A_Continuation] using that dump is becoming
		 * immutable or shared.
		 *
		 * @param dump
		 *   The [A_RegisterDump] containing saved register state.
		 * @param encodedIndex
		 *   An [Int] produced by [encodeLocalValue] for capturing the value for
		 *   initializing a local variable.
		 * @return
		 *   The [AvailObject], perhaps freshly created from an unboxed form,
		 *   suitable for initializing a local variable that has been elided up
		 *   to this point.
		 */
		fun decodeBoxedValueFromDump(
			dump: A_RegisterDump,
			encodedIndex: Int
		): AvailObject = when
		{
			encodedIndex == 0 -> unsupported
			encodedIndex > 0 -> dump.extractDumpedObjectAt(encodedIndex)
			encodedIndex and 1 == 0 -> fromInt(
				dump.extractDumpedLongAt(-encodedIndex ushr 1).toInt())
			else -> fromDouble(
				longBitsToDouble(
					dump.extractDumpedLongAt(-encodedIndex ushr 1))).cast()
		}

		/**
		 * Extract the tuple of elided local information from this register
		 * dump.  The information is encoded as per [ENCODED_ELIDED_LOCALS].
		 */
		val A_RegisterDump.encodedElidedLocals: A_Tuple
			get() = dispatch { o_EncodedElidedLocals(it) }

		/**
		 * A [CheckedMethod] for invoking the method [extractDumpedObjectAt].
		 */
		val extractDumpedObjectAtMethod = instanceMethod(
			A_RegisterDump::class.java,
			A_RegisterDump::extractDumpedObjectAt.name,
			AvailObject::class.java,
			Int::class.javaPrimitiveType!!)

		/**
		 * A [CheckedMethod] for invoking the method [extractDumpedLongAt].
		 */
		val extractDumpedLongAtMethod = instanceMethod(
			A_RegisterDump::class.java,
			A_RegisterDump::extractDumpedLongAt.name,
			Long::class.javaPrimitiveType!!,
			Int::class.javaPrimitiveType!!)
	}
}
