{
  "formatVersion": "1.1",
  "component": {
    "group": "org.availlang",
    "module": "avail-json",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "avail-json-1.0.7.jar",
          "url": "avail-json-1.0.7.jar",
          "size": 47172,
          "sha512": "c344137e9ca0f85d2f83919fb6b980abf1cddf679d07c1d6e86dccbe3989ece286e24e28538f580d9df5cd182e465e740e34658f1c9babb087bb627acf40f6af",
          "sha256": "db0b2e61e83e89062b404b4792c7f7e7a8dc6e3a3f3f5db13137798fd5eab780",
          "sha1": "d6653d9fadceb6221f0164428fb631ee45443404",
          "md5": "e9700c13425a25a696aa882a557075bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "avail-json-1.0.7.jar",
          "url": "avail-json-1.0.7.jar",
          "size": 47172,
          "sha512": "c344137e9ca0f85d2f83919fb6b980abf1cddf679d07c1d6e86dccbe3989ece286e24e28538f580d9df5cd182e465e740e34658f1c9babb087bb627acf40f6af",
          "sha256": "db0b2e61e83e89062b404b4792c7f7e7a8dc6e3a3f3f5db13137798fd5eab780",
          "sha1": "d6653d9fadceb6221f0164428fb631ee45443404",
          "md5": "e9700c13425a25a696aa882a557075bf"
        }
      ]
    }
  ]
}
