site_name: 'Avail Implementation Documentation'
copyright: Copyright &copy; 1993-2020, The Avail Foundation, LLC.<br>All rights reserved.

# Repository
repo_name: Avail
repo_url:  https://github.com/AvailLang/Avail
edit_uri: ""

theme:
  name: material
  logo: 'img/AvailHammer.png'
  highlightjs: true
  features:
    - tabs
  favicon: 'img/favicon.ico'

extra_css:
  - css/extra.css

markdown_extensions:
  - smarty
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - tables

nav:
  - 'Avail Implementation':
    - Packages: src_docs/avail/index.md
    - Types: src_docs/avail/alltypes/index.md
  - 'Avail Server':
    - Packages: src_docs/avail-server/index.md
    - Types: src_docs/avail-server/alltypes/index.md
  - 'Avail Bootstrap':
    - Packages: src_docs/avail-bootstrap/index.md
    - Types: src_docs/avail-bootstrap/alltypes/index.md
  - 'Avail Workbench':
    - Packages: src_docs/avail-workbench/index.md
    - Types: src_docs/avail-workbench/alltypes/index.md
  - 'Avail CLI':
    - Packages: src_docs/avail-cli/index.md
    - Types: src_docs/avail-cli/alltypes/index.md
  - 'Unicode Catalog':
    - Packages:  src_docs/unicode-catalog/index.md
    - Types: src_docs/unicode-catalog/alltypes/index.md
  - 'Index File Anaylzer':
    - Packages:  src_docs/indexed-file-analyzer/index.md
    - Types: src_docs/indexed-file-analyzer/alltypes/index.md
